Repository hearai/hearai, pull requests merged in 2022-03, with the labels that each got.

#56 Train.py gpu param fix
  train.py
Labels: bug

#55 Feature/freeze scheduler
  README.md
  models/model.py
  train.py
  train_config.yml
  train_config_default.yml
Labels: enhancement

#58 fix
  models/transformers/sign_language_transformer.py
Labels: bug

#61 GPU MisconfigurationException fix
  train.py
Labels: bug

#65 fixing bug in model performance estimation
  models/model.py
Labels: bug

#78 Ggoryl landmarks
  datasets/dataset.py
  datasets/dataset_creator.py
  models/features_sequential_model.py
  models/lanmdarks_sequential_model.py
  models/model.py
  train_config.yml
Labels: enhancement

#88 Fix for representation size in model_for_pretraining.py
  models/model_for_pretraining.py
Labels: bug

#92 Ggoryl final approach
  models/feature_extractors/conv1d_features_processor.py
  models/landmarks_models/features_sequential_model.py
  models/landmarks_models/lanmdarks_sequential_model.py
  models/model.py
  models/model_loader.py
  models/transformers/__init__.py
  models/transformers/sign_language_cnn_transformer.py
  models/transformers/sign_language_transformer.py
  train.py
  train_config_cnn_transformer.yml
Labels: bug, enhancement, model
